label CENA11:
    "Ahhh..."
    "*Suspiro*"
    "Virar a noite atrás de pistas não é trabalho para qualquer pessoa…"
    "Preciso me apressar, marquei de me encontrar às três em ponto!"
    "E já tardam duas e quarenta …"
    "Pegar casos seguidos é realmente um péssimo hábito…"
    #Tamanho ideal: 1280px x 720px
    scene cidade
    "*Chega na cidade*"
    "É realmente uma bela cidade... Não tinha notado a sua existência até o telefonema do advogado de uma família envolvida, ontem a noite."
    "Agora ... Pra que lado será a edificação que marcamos o encontro?"
    "*Ouve alguém chamado*"
    #Tamanho ideal : 650px x 460px
    show sheppard neutro at center
    shp "Detetive Rightclue!"
    drc "Ora ... Senhor Sheppard?"
    shp "Sim, exatamente."
    drc "É um prazer!"
    shp "Prazer!"
    shp "Fico grato que tenha vindo detetive. Estamos com sérios problemas por aqui!"
    drc "Não sei dos detalhes, mas de fato ouvi do chefe ser um caso complexo e perigoso."
    shp "Sim, exato. Vamos até o escritório, é a edificação logo a frente."
    "*Vão para o escritório*"
    shp "Sente-se detetive."
    drc "Agradeço."
    "*Ambos sentam*"
    shp "Senhor Rightclue, o que aconteceu aqui é um caso sério. Uma pessoa importante foi assassinada."
    drc "Pelo que consta no relatório, Senhor Cashand, correto?"
    shp "Exato! Os Cashand são famosos em Anothertown por serem ricos há certas décadas."
    shp "Todavia senhor Rightclue, para lhe dar melhores informações, necessito que o senhor se comprometa conosco."
    "*Sheppard saca um contrato de uma gaveta*"
    shp "O que o senhor ouvirá à partir de agora, Senhor Rightclue, terá de ser confidencial, compreende?"
    drc "Estou de acordo. Fui orientado a somente resolver o caso, e nada mais."
    shp "O senhor foi indicado como sendo de confiança, todavia, peço para que assine estes termos."
    "Termos são mostrados Fala sobre manter absoluto sigilo e que concorda com o perigo envolvido no caso podia ser uma arte de um contrato na tela mesmo."
    drc "Aí está senhor Sheppard."
    shp "Ótimo. Pois bem, vamos aos fatos…"
    shp "Tudo começou há 38 anos atrás, quando Hougin Cashand inicia com os negócios."
    drc "Que tipo de negócios o senhor diz?"
    shp "Negócios, senhor Rightclue. Hougin era, e creio que por muito tempo ainda será, o maior mafioso desse estado. O senhor compreende?"
    shp "Não é por nada que o senhor Cashand possui tantos bens. Um jogo obscuro foi jogado senhor detetive, por quatro longas décadas."
    drc "Pois então, devo considerar que estou entrando em terreno obscuro."
    shp "Não há motivo para alarde detetive. O homem qual sustava esse reino está, nesse exato momento, há um metro e oitenta sob a terra qual reinou."
    shp "Mas alguém há de tomar seu lugar, herdar sua fortuna"
    shp "Pois bem. Haviam cinco pessoas que estão na lista para reivindicar o tesouro do senhor Hougin Cashand."
    shp "São eles:"
    #Ver de trocar a apresentacao pra hora que eles se encontrarem
    shp "Joe Cashand, filho legítimo de Hougin com sua primeira esposa. Temperamental, um pouco atacado pela soberba, mas é um bom rapaz. Garanto ao senhor."
    shp "Kamira Thereza Cashand, sobrinha do senhor Hougin, decidida e com forte senso de justiça."
    shp "Hugo Theodore Cashand, segundo filho desse senhor da máfia, sem ligar muito para etiqueta, hoje ele vive com seu cachorro em uma Kombi, próximo à mansão dos Cashand, podemos dizer que é do tipo rebelde com a família."
    shp "Catherine Vladita Cashand, irmã mais nova do senhor Hougin, apesar de um tom sereno e maduro, é apenas 8 anos mais velha que seu sobrinho Hugo."
    shp "O último herdeiro era Lostie Annou Cashand, segundo irmão mais novo do senhor Hougin Cashand, que fora assassinado esta noite."
    drc "Intrigante... Podemos afirmar que os assassinatos ocorreram pelo interesse nos bens do senhor Hougin, creio eu. Talvez alguém interessado em lesar a família e ficar com o dinheiro?"
    shp "De fato. Acredito ser totalmente coerente com a situação, visto que o senhor Hougin andava ruim de saúde."
    shp "Todavia, ele não morreu devido à sua doença. Foi encontrado no terceiro quarto do segundo andar da mansão dos Cashand, apunhalado no peito."
    drc "E o senhor Lostie?"
    shp "Com o pescoço quebrado, próximo ao jardim da mansão." #revisar
    drc "Entendo. Estou desde o início de nossa conversa pensando, por que se envolveu senhor Sheppard?"
    shp "O fato é que como advogado e amigo do senhor Hougin, digo que essa situação não pode continuar."
    shp "Pouco antes de morrer ele me pagou uma excelente quantia extra por todos meus anos de serviço, e me pediu para que cuidasse de sua família caso ele viesse a falecer devido a sua doença."
    drc "O senhor fala como se tivesse esse dever. Todavia, ele não está mais aqui para o senhor argumentar que estaria se envolvendo em um caso de assassinato."
    shp "De fato. Mas ainda sim, meu orgulho fala mais alto senhor Rightclue, meu dever terá de ser cumprido."
    shp "Hum Hum. O senhor tem meu respeito senhor Sheppard. Pode contar comigo nesse caso."
    "*Sheppard se levanta*"
    shp "Estava certo que poderia contar com o senhor, detetive."

jump CENA12
