label CENA34:
    ##scene hall
    #with Fade(7, 4, 0.5)

    #show hugo maniaco
    hugo "Meus parabéns seu maldito. Salvou o dia. Seu desgraçado."
    hugo "Era melhor que nunca tivesse aparecido, sua peste."
    hugo "O senhor pensa que acabou?"
    hugo "O senhor acha que está resolvido?"
    hugo "Ahahahahaha"
    hugo "Engano o seu. Eu irei buscá-lo detetive..."
    hugo "Irei sim."
    #show carlo neutro
    carlo "Cale a boca."
    carlo "Teremos muito o que conversar ainda hoje."
    hugo "Aaaaaaaaahhhhhhhh"
    hugo "Me larguem seus porcos."
    hugo "Vou acabar com vocês."
    hugo "Acham que conseguem me matar?"
    hugo "Pois veremos."
    hugo "Veremos"
    hugo "Ahahahahahahaha..."
    "*Ouve latido. Thorn aparece.*"
    hugo "Thorn, não!"
    "*Thorn tenta atacar Carlo Venchinni.*"
    carlo "Vira-lata imundo. Matem ele."
    hugo "Thorn! Fuja! Agora!"
    hugo "Gunis atendum kfvok."
    "*Som de tiro*"
    "*Thorn foge*"
    carlo "Maldito cão. Fugiu."
    carlo "Mas não importa."
    carlo "Levem ele."
    hugo "Ahahahaha."
    hugo "Isso. Me levem. Me levem."
    "..."
    carlo "Assim, me despeço do senhor, Detetive Rightclue."
    drc "Fico grato, senhor Venchinni."
    drc "Garantirei sigilo de tudo que ocorreu aqui. Tem minha palavra."
    carlo "Excelente."
    carlo "Sheppard confiou em você. Fiz certo ao confiar também."
    drc "Até mais, senhor Venchinni"
    #hide venchinni
    #hide hugo maniaco
    joe "..."
    cth "..."
    drc "Bom, meu trabalho termina aqui."
    joe "Senhor Rightclue. Eu nem sei o que dizer. Sinto que recebemos o senhor de forma tão áspera."
    joe "Mas se não fosse o senhor, não conseguiríamos nos salvar."
    drc "É meu trabalho, senhor Joe."
    drc "Estou arrasado. Perderam mais duas pessoas no período que estive aqui. Eu realmente sinto muito."
    cth "A justiça foi feita senhor. Estamos arrasados. Joe e eu temos apenas um ao outro agora."
    cth "Mas saberemos que estamos seguros."
    joe "..."
    cth "Sairemos daqui. Esse lugar está manchado demais com o sangue de nossa família."
    joe "Eu irei para outro lugar. Recomeçar. Mas parece que ainda estou em um pesadelo."
    cth "Eu também irei. Esse lugar, essa vida. Acho que está na hora de recomeçar. Em outro lugar."
    drc "Entendo."
    drc "Bom. Desejo toda a sorte do mundo aos dois."
    joe "Muito obrigado ao senhor."
    cth "Obrigada por ficar e fazer justiça."
    drc "É meu trabalho."
    drc "Bom, me despeço por aqui."
    drc "Até mais a vocês."
    joe "Até mais, senhor Rightclue."
    cth "Até mais detetive, e obrigada."
    #hide Joe
    #hide Catherine
    jump CENA35
