label CENA22:
    scene velorio
    with Fade(3, 2, 0.5)
    "*Funeral ao fundo é mostrado*"
    "*A se aproxima do senhor Rightclue*"
    ind_a "Senhor Rightclue."
    "*Rightclue se recompõe de seus pensamentos e com tom investigativo, indaga*"
    drc "Olá [ind_a_info[1]]. Meus pêsames pela perda. O senhor Sheppard realmente se importava com vocês."
    ind_a "Sim, senhor Rightclue. Apesar de tudo, Sheppard era como um membro da família. Vou sentir sua falta."
    "*[ind_a_info[0]] enxuga uma lágrima*"
    drc "Dou minha palavra a você [ind_a_info[1]]. Prometo achar o culpado por tudo isso."
    ind_a "Deixo em suas mãos, detetive."
    "*[ind_a_info[0]] se afasta*"
    "Se o responsável por isso pensa que sairá impune, juro por minha honra que não irá!"
    "Farei justiça pelo senhor Sheppard. O culpado será preso. Ajudarei os herdeiros a se livrarem desse traidor!"
    "..."
    "Realmente como me foi dito. Como manda o costume da cidade, enterrarão o senhor Sheppard ainda agora de manhã."
    "Humm..."
    "Joe Cashand não saiu por nem um segundo do lado do corpo do Senhor Sheppard."
    "..."
    "Algo me chama atenção..."
    "Preciso investigar mais sobre as relações dos herdeiros com cada membro da família."
    "Hugo está vindo..."
    "..."
    "Parou próximo. Irei até ele."
    "Não tenho necessariamen..."
    desconhecido "Senhor Rightclue, eu suponho?"
    "..."
    "*Rightclue se vira*"
    #show carlo aqui
    drc "Sim, exato. E qual seria sua graça, senhor?"
    desconhecido "O Senhor me conhece, Senhor Rightclue. E sugiro que se lembre rapidamente. E falemos baixo, sim?"
    drc "Suponho, pela voz, que o senhor seja Carlo Venchinni."
    carlo "Vejo que o senhor tem astúcia."
    carlo "Senhor Rightclue, deixe-me dizer uma coisa..."
    carlo "Estou tão furioso que mataria todos esses malditos, um após um, ao sairem desse velório."
    carlo "Detetive, tive uma dívida com Sheppard, qual nunca poderei pagar. Por mim, eliminaria, na dúvida, todos os herdeiros do velho que estão aqui."
    drc "..."
    carlo "Porém, o Senhor Sheppard realmente tinha apreço por essa família. E confiava em você para resolver o caso."
    carlo "Deixe-me dizer mais uma coisa..."
    carlo "O senhor tem até o anoitecer de amanhã. Seu horário limite são as 10 da noite."
    carlo "Se o senhor não me entregar o culpado até lá, matarei todos esses vermes."
    carlo "Um após um..."
    carlo "Sem nenhuma piedade."
    carlo "Vingarei Sheppard. E sugiro que o senhor se retire da casa até essa data e hora."
    carlo "O senhor entendeu?"
    drc "Perfeitamente senhor."
    carlo "Perfeito. Você tem um trabalho a cumprir. Cumpra-o. Eu terei o meu. O destino desses desgraçados está em suas mãos."
    drc "Estou de acordo, Senhor Venchinni."
    carlo "Ótimo. Que assim seja."
    #hide carlo com um dissolve talvez
    "Meu deus. Tenho um fardo grande para carregar."
    "..."
    "Hugo se foi."
    "O tempo está correndo. Preciso me apressar. Hoje e amanhã serão cruciais."
    jump CENA23
