label CENA21:
    "*Batidas apressadas à porta*"
    mrth "Senhor Rightclue!"
    mrth "Senhor Rightclue!"
    scene cidade
    "*Rightclue se levanta*"
    drc "Sim Martha? São apenas três da manhã."
    mrth "É o Sheppard, senhor! Foi encontrado morto no banheiro de seu quarto!"
    "*Rightclue se levanta as pressas*"
    drc "Não. Não. Não"
    "*Abre a porta e vai pro corredor com Martha*"
    drc "Não. Não. Não. Não. Não"
    drc "Não..."
    "*Rightclue entra no quarto de Sheppard, ao lado*"
    drc "Não... Não..."
    "--->*Rightclue encontra Sheppard caido, com sangue em volta*"
    drc "Sheppard.... Por que? Por que?"
    drc "*Por que?"
    drc "Por que eu tomei aquela decisão em relação a contá-lo. Me desculpe Sheppard. Me desculpe..."
    "..."
    jump CENA22
